In [1]:
#Below are lists of Bitcoin's quarterly prices from 2014 to 2022.

Bitcoin_2014 = [457.00, 639.80, 386.94, 320.19]
Bitcoin_2015 = [244.22, 263.07, 236.06, 430.57]
Bitcoin_2016 = [416.73, 673.34, 609.74, 963.74]
Bitcoin_2017 = [1072, 2481, 4339, 14156]
Bitcoin_2018 = [6954, 6398, 6619, 3767]
Bitcoin_2019 = [4081, 10874, 8280, 7193]
Bitcoin_2020 = [6435, 9142, 10754, 29033]
Bitcoin_2021 = [58945, 34922, 43776, 46313]
Bitcoin_2022 = [45573, 19709, 19423, 16536]

In [2]:
Bitcoin_2014to2022 = []

for i in range(14,23):
    for j in globals()['Bitcoin_20'+str(i)]:
        Bitcoin_2014to2022.append(j)

import numpy as np
Bitcoin_2014to2022_Array = np.array(Bitcoin_2014to2022)
print(Bitcoin_2014to2022_Array)
print(Bitcoin_2014to2022_Array.mean())
print(Bitcoin_2014to2022_Array.mean(), Bitcoin_2014to2022_Array.max(), Bitcoin_2014to2022_Array.min(),Bitcoin_2014to2022_Array.max() - Bitcoin_2014to2022_Array.min())

[  457.     639.8    386.94   320.19   244.22   263.07   236.06   430.57
   416.73   673.34   609.74   963.74  1072.    2481.    4339.   14156.
  6954.    6398.    6619.    3767.    4081.   10874.    8280.    7193.
  6435.    9142.   10754.   29033.   58945.   34922.   43776.   46313.
 45573.   19709.   19423.   16536.  ]
11733.78888888889
11733.78888888889 58945.0 236.06 58708.94


In [4]:
#1. Find the average prices for each year (2014 to 2022) 
#   by converting all the lists into numpy arrays 
#   and using the average function.

#Basic Solution
import numpy as np

BTC_Array_2014 = np.array(Bitcoin_2014)
BTC_Array_2015 = np.array(Bitcoin_2015)
BTC_Array_2016 = np.array(Bitcoin_2016)
BTC_Array_2017 = np.array(Bitcoin_2017)
BTC_Array_2018 = np.array(Bitcoin_2018)
BTC_Array_2019 = np.array(Bitcoin_2019)
BTC_Array_2020 = np.array(Bitcoin_2020)
BTC_Array_2021 = np.array(Bitcoin_2021)
BTC_Array_2022 = np.array(Bitcoin_2022)

print("The average price of Bitcoin in 2014:",BTC_Array_2014.mean())
print("The average price of Bitcoin in 2015:",BTC_Array_2015.mean())
print("The average price of Bitcoin in 2016:",BTC_Array_2016.mean())
print("The average price of Bitcoin in 2017:",BTC_Array_2017.mean())
print("The average price of Bitcoin in 2018:",BTC_Array_2018.mean())
print("The average price of Bitcoin in 2019:",BTC_Array_2019.mean())
print("The average price of Bitcoin in 2020:",BTC_Array_2020.mean())
print("The average price of Bitcoin in 2021:",BTC_Array_2021.mean())
print("The average price of Bitcoin in 2022:",BTC_Array_2022.mean())

#A More Elegant Solution
print(len(Bitcoin_2014))
BTC = np.zeros(shape=(22-14+1, len(Bitcoin_2014)))

print(BTC)
print()

for i in range(14,23):
    BTC[i-14] = globals()['Bitcoin_20'+str(i)]

for i in range(len(BTC)):
    print("Mean Price 20"+str(i+14)+':',BTC[i].mean())

The average price of Bitcoin in 2014: 450.9825
The average price of Bitcoin in 2015: 293.47999999999996
The average price of Bitcoin in 2016: 665.8875
The average price of Bitcoin in 2017: 5512.0
The average price of Bitcoin in 2018: 5934.5
The average price of Bitcoin in 2019: 7607.0
The average price of Bitcoin in 2020: 13841.0
The average price of Bitcoin in 2021: 45989.0
The average price of Bitcoin in 2022: 25310.25
4
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Mean Price 2014: 450.9825
Mean Price 2015: 293.47999999999996
Mean Price 2016: 665.8875
Mean Price 2017: 5512.0
Mean Price 2018: 5934.5
Mean Price 2019: 7607.0
Mean Price 2020: 13841.0
Mean Price 2021: 45989.0
Mean Price 2022: 25310.25


In [77]:
#2. Create a new numpy array of the average yearly prices. 
#   Find the minimum average price and the maximum average price.

BTC_MeanPrice = np.array([BTC_Array_2014.mean(), BTC_Array_2015.mean(), BTC_Array_2016.mean(), BTC_Array_2017.mean(), BTC_Array_2018.mean(), BTC_Array_2019.mean(), BTC_Array_2020.mean(), BTC_Array_2020.mean(), BTC_Array_2021.mean(), BTC_Array_2022.mean()])

print("Minimum Average Price of BTC:" ,BTC_MeanPrice.min())
print("Maximum Average Price of BTC:" ,BTC_MeanPrice.max())

Minimum Average Price of BTC: 293.47999999999996
Maximum Average Price of BTC: 45989.0


In [79]:
#3. Find the overall minimum and maximum price of Bitcoin from 2014 to 2022. Calculate the difference.
count_10000 = 0
count_20000 = 0
count_30000 = 0
count_under4figs = 0 

for i in range(len(BTC)):
    for j in BTC[i]:
        if j > 10000:
            count_10000 += 1
        if j > 20000:
            count_20000 += 1
        if j > 30000:
            count_30000 += 1
        if j < 1000:
            count_under4figs += 1
            
print("Quarters over 10000:",count_10000)
print("Quarters over 20000:",count_20000)
print("Quarters over 30000:",count_30000)
print("Quarters under 4 figures:",count_under4figs)

Quarters over 10000: 12
Quarters over 20000: 6
Quarters over 30000: 5
Quarters under 4 figures: 12


In [80]:
#5. We can use for to search through arrays like we used for lists. 
#   i. Write a program that searches through the list you made and counts
#      the number of quarters Bitcoin closed over 10000, 20000, and 30000.
#  ii. Included in the script for i., also count the number of quarters
#      Bitcoin closed under 4 figures.

count_10000 = 0
count_20000 = 0
count_30000 = 0
count_under4figs = 0 

for i in range(len(BTC)):
    for j in BTC[i]:
        if j > 10000:
            count_10000 += 1
        if j > 20000:
            count_20000 += 1
        if j > 30000:
            count_30000 += 1
        if j < 1000:
            count_under4figs += 1
            
print("Quarters over 10000:",count_10000)
print("Quarters over 20000:",count_20000)
print("Quarters over 30000:",count_30000)
print("Quarters under 4 figures:",count_under4figs)

Quarters over 10000: 12
Quarters over 20000: 6
Quarters over 30000: 5
Quarters under 4 figures: 12
